# fly.toml app configuration file generated for bot-id-shadow-lively-haze-6086 on 2024-12-07T07:56:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-id-shadow-lively-haze-6086'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
